version: '3'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ss_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: